[package]
name = "lucet-spectest"
version = "0.1.0"
authors = ["Pat Hickey <phickey@fastly.com>"]
license = "Apache-2.0 WITH LLVM-exception"
edition = "2018"

[lib]
crate-type=["rlib"]

[[bin]]
name = "spec-test"
path = "src/main.rs"

[dependencies]
lucetc = { path = "../lucetc" }
lucet = { path = "../lucet-rs" }
parity-wasm = "0.35"
wabt = "0.7"
serde = "1.0"
serde_json = "1.0"
failure = "0.1"
clap="2.32"
tempdir = "0.3"
