dist: xenial

env:
  - DEVENV_NO_INSTALL=1

services:
  - docker

before_install:
  - ./devenv_build_container.sh
  - ./devenv_start.sh

script:
  - ./devenv_run make indent-check test audit
  - git diff --exit-code

notifications:
  email: false
