dist: xenial

services:
  - docker

before_install:
  - ./devenv_build_container.sh
  - ./devenv_start.sh

script:
  - docker exec -t -w /lucet lucet make indent-check test audit
  - git diff --exit-code

notifications:
  email: false
