[workspace]
members = [
  "lucet-analyze",
  "lucet-idl",
  "lucet-module-data",
  "lucet-runtime",
  "lucet-runtime/lucet-runtime-internals",
  "lucet-runtime/lucet-runtime-tests",
  "lucet-spectest",
  "lucet-wasi-sdk",
  "lucetc",
  "sightglass",
]
exclude = ["cranelift"]

[profile.test]
rpath = true

[replace]
"faerie:0.8.0" = { path = "faerie" }
