[package]
name = "lucet-idl"
version = "0.1.0"
authors = ["Pat Hickey <phickey@fastly.com>"]
repository = "https://github.com/fastly/isolation"
license = "Apache-2.0 WITH LLVM-exception"
edition = "2018"

[lib]
crate-type=["rlib"]

[dependencies]
